version: "3.9"
services:

      # Oracle service (label used to access the service container)
      oracle:

        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-xe:11

        #volumes:
        #  - ./volume:/u01/app/oracle/oradata

        # Provide passwords and other environment variables to container
        environment:
          ORACLE_RANDOM_PASSWORD: "true"
          APP_USER: test
          APP_USER_PASSWORD: test
        
        privileged: true

        # Forward Oracle port
        ports:
          - 1521:1521
